#!/bin/sh

UOKOHIWIFI_STATUS_FILE="/tmp/.uokohiwifi/status"

install()
{
	#mkdir -p "$HOME"/bin "$HOME"/etc
	#cp ./uokohiwifi.lua "$HOME"/bin/
	#cp ./cacert.pem ./uokohiwifi.conf "$HOME"/etc/
	rm /etc/nginx/vh.tw.conf
	cp ./vh.tw.conf /etc/nginx/vh.tw.conf
	start
}

uninstall()
{
	stop
}

start()
{
	nginx -s reload
}

stop()
{

}

status()
{
	
}