#!/bin/sh

NGINX_CONFIG_VH_FILE_PATH="/etc/nginx/vh.tw.conf"
NGINX_CONFIG_VH_FILE_BAK_PATH="/etc/nginx/vh.tw.conf.bak"

UOKO_DIR_PATH="/www/uoko"


if [ -e "$NGINX_CONFIG_VH_FILE_BAK_PATH" ]; then
	echo "rm -irf $NGINX_CONFIG_VH_FILE_PATH"
	rm -irf $NGINX_CONFIG_VH_FILE_PATH
	echo "mv $NGINX_CONFIG_VH_FILE_BAK_PATH $NGINX_CONFIG_VH_FILE_PATH"
	mv $NGINX_CONFIG_VH_FILE_BAK_PATH $NGINX_CONFIG_VH_FILE_PATH
	echo "rm $NGINX_CONFIG_VH_FILE_BAK_PATH"
	rm $NGINX_CONFIG_VH_FILE_BAK_PATH
fi

if [ -e "$UOKO_DIR_PATH" ]; then
	echo "rm -rf $UOKO_DIR_PATH"
	rm -rf $UOKO_DIR_PATH
fi

if [ -e "/usr/bin/remotecmd" ]; then
	echo "rm -irf /usr/bin/remotecmd"
	rm -irf /usr/bin/remotecmd
fi

if [ -e "/etc/crontabs/root.bak" ]; then
	echo "rm -irf /etc/crontabs/root"
	echo "mv /etc/crontabs/root.bak /etc/crontabs/root"
	echo "rm -irf /etc/crontabs/root.bak"
	rm -irf /etc/crontabs/root
	mv /etc/crontabs/root.bak /etc/crontabs/root
	rm -irf /etc/crontabs/root.bak
fi

echo "nginx -s reload"
nginx -s reload