#!/bin/sh

NGINX_CONFIG_VH_FILE_PATH="/etc/nginx/vh.tw.conf"
NGINX_CONFIG_VH_FILE_BAK_PATH="/etc/nginx/vh.tw.conf.bak"
NGINX_CONFIG_VH_CHK_FILE_PATH="/etc/nginx/vh.tw-netchk.conf"
NGINX_CONFIG_VH_CHK_FILE_BAK_PATH="/etc/nginx/vh.tw-netchk.conf.bak"

UOKO_DIR_PATH="/www/uoko"


echo -e "\033[32m!!!begin uninstall!!!\033[0m"

if [ -e "$NGINX_CONFIG_VH_CHK_FILE_BAK_PATH" ]; then
	echo "rm -irf $NGINX_CONFIG_VH_CHK_FILE_PATH"
	rm -irf $NGINX_CONFIG_VH_CHK_FILE_PATH
	echo "mv $NGINX_CONFIG_VH_CHK_FILE_BAK_PATH $NGINX_CONFIG_VH_CHK_FILE_PATH"
	mv $NGINX_CONFIG_VH_CHK_FILE_BAK_PATH $NGINX_CONFIG_VH_CHK_FILE_PATH
fi

if [ -e "$NGINX_CONFIG_VH_FILE_BAK_PATH" ]; then
	echo "rm -irf $NGINX_CONFIG_VH_FILE_PATH"
	rm -irf $NGINX_CONFIG_VH_FILE_PATH
	echo "mv $NGINX_CONFIG_VH_FILE_BAK_PATH $NGINX_CONFIG_VH_FILE_PATH"
	mv $NGINX_CONFIG_VH_FILE_BAK_PATH $NGINX_CONFIG_VH_FILE_PATH
fi

if [ -e "$UOKO_DIR_PATH" ]; then
	echo "rm -rf $UOKO_DIR_PATH"
	rm -rf $UOKO_DIR_PATH
fi

if [ -e "/usr/bin/remotecmd" ]; then
	echo "rm -irf /usr/bin/remotecmd"
	rm -irf /usr/bin/remotecmd
fi

if [ -e "/etc/hosts.bak" ]; then
	echo "rm -irf /etc/hosts"
	echo "mv /etc/hosts.bak /etc/hosts"
	rm -irf /etc/hosts
	mv /etc/hosts.bak /etc/hosts
fi

if [ -e "/etc/crontabs/root.bak" ]; then
	echo "rm -irf /etc/crontabs/root"
	echo "mv /etc/crontabs/root.bak /etc/crontabs/root"
	echo "rm -irf /etc/crontabs/root.bak"
	rm -irf /etc/crontabs/root
	mv /etc/crontabs/root.bak /etc/crontabs/root
	rm -irf /etc/crontabs/root.bak
fi

echo "/etc/init.d/wifidog stop"
/etc/init.d/wifidog stop

echo "nginx -s reload"
nginx -s reload

echo -e "\033[32m!!!completed all!!!\033[0m"